### 第7章 错误处理
错误处理只不过是编程时必须要做的事之一,输入可能出现异常,设备可能失效.简言之,可能会出错,当错误发生时,程序员就有责任确保代码照常
工作.  
然而,应该弄清楚错误处理与整洁代码的关系.许多程序完全由错误处理所占据.所谓占据,并不是说错误处理就是全部.我的意思是几乎无法看明白
代码所做的事,因为到处都是凌乱的错误处理代码.错误处理很重要,但如果它搞乱了代码逻辑,就是错误的做法.  
在本章中,我将要列出编写既整洁又强固的代码--雅致地处理错误代码的一些技巧和思路. 

#### 7.1 使用异常而非返回码
在很久以前,许多语言都不支持异常.这些语言处理和汇报错误的手段都有限.你要么设置一个错误标识,要么返回给调用者检查的错误码.下面代码
展示了这些手段.
```java
public class DeviceController {
    public void sendShutDown() {
        DeviceHandle handle = getHandle(DEV1);
        //Check the state of the device
        if (handle != DeviceHandle.INVALID) {
            //Save the device status to the record field
            retrieveDeviceRecord(handle);
            //If not suspended, shut down
            if (record.getStatus() != DEVICE_SUSPENDED) {
                pauseDevice(handle);
                clearDeviceWorkQueue(handle);
                closeDevice(handle);
            } else {
                logger.log("Device suspended. Unable to shut down");
            }
        } else {
            logger.log("Invalid handle for:" + DEV1.toString());
        }
    }
}
```
这类手段的问题在于,它们搞乱了调用者代码.调用者必须在调用之后即刻检查错误.不幸的是,这个步骤很容易被遗忘.所以,遇到错误时,最好抛出
一个异常.调用代码很整洁,其逻辑不会被错误处理搞乱.  
下面展示了在方法中遇到错误时抛出异常的情形.  
```java
public class DeviceController {
    public void sendShutDown() {
        try {
            tryToShutDown();
        } catch (DeviceShutDownError e) {
            logger.log(e);
        }
    }
    private void tryToShutDown() throws DeviceShutDownError {
        DeviceHandle handle = getHandle(DEV1);
        DeviceRecord record = retrieveDeviceRecord(handle);
        pauseDevice(handle);
        clearDeviceWorkQueue(handle);
        closeDevice(handle);
    }
    private DeviceHandle getHandle(DeviceID id) {
        //...
        throw new DeviceShutDownError("Invalid handle for:" + id.toString());
        //...
    }
    //...
}
```
注意这段代码整洁了很多.这不仅关乎美观.这段代码更好,因为之前纠结的两个元素设备关闭算法和错误处理现在被隔离了.你可以查看其中任一
元素,分别理解它.

#### 7.2 先写Try-Catch-Finally语句
异常的妙处之一是,它们在程序中定义了一个范围.执行Try-Catch-Finally语句中try部分的代码时,你是在表明可随时取消执行,并在catch语句
中接续.  
在某种意义上,try代码块就像是事务. catch代码块将程序维持在一种持续状态,无论try代码块中发生了什么均如此.所以,在编写可能抛出异常
的代码时,最好先写出try-catch-finally语句.这能帮你定义代码的用户应该期待什么,无论try代码块中执行的代码出什么错都一样.  
我们要编写访问某个文件并读出一些序列化对象的代码.  
先写一个单元测试,其中显示当文件不存在时将得到一个异常:  
```java
public class Test {
    @Test(expected = StorageException.class)
    public void retrieveSectionShouldThrowOnInvalidFileName() {
        sectionStore.retrieveSection("invalid - file");
    }
    //该测试驱动我们创建以下占位代码
    public List<RecordGrip> retrieveSection(String sectionName) {
        // dummy return until we have a real implementation
        return new ArrayList<> ();
    }
    //测试失败了,因为以上代码并未抛出异常.下一步,修改实现代码,尝试访问非法文件.该操作抛出一个异常:
    public List<RecordedGrip> retrieveSection(String sectionName) {
        try {
            FileInputStream stream = new FileInpuStream(sectionName);
        } catch (Exception e) {
            throw new StorageException("retrieval error", e);
        }
        return new ArrayList<>();
    }
    //这次测试通过了,因为我们捕获了异常.此时,我们可以重构了.我们可以缩小异常类型的范围,使之符合FileInputStream构造器真正抛出的
    //异常,即FileNotFoundException:
    public List<RecordedGrip> retrieveSection(String sectionName) {
        try {
            FileInputStream stream = new FileInputStream(sectionName);
            stream.close();
        } catch (FileNotFoundException e) {
            throw new StorageException("retrieval error", e);
        }
        return new ArrayList<>();
    }
}
```
如此一来,我们就用try-catch结构定义一个范围,可以继续用测试驱动(TDD)方法构建剩余的代码逻辑.这些代码逻辑将在FileInputStream和
close之间添加,装作一切正常的样子.  
尝试编写强行抛出异常的测试,再往处理器中添加行为,使之满足测试要求.结果就是你要先构造try代码块的事务范围,而且也会帮助你维护好
该范围的事务特征.

#### 7.3 使用不可控异常
可控异常的利与弊.代价是什么?可控异常的代价就是违反开放/闭合原则.如果你在方法重抛出可控异常,而catch语句在三个层级之上,你就得在
catch语句和抛出异常处之间的每个方法签名重声明该异常.这意味着对软件中较低层级的修改,都将波及较高层级的签名.修改好的模块必须重新
构建、发布,即便他们自身所关注的任何东西都没改动过.  
以某个大型系统的调用层级为例.顶端函数调用它们之下的函数,逐级向下.假设某个位于最底层级的函数呗修改为抛出一个异常.如果该异常是可
控的,则函数签名就要添加throw子句.这意味着每个调用该函数的函数都要修改,捕获新异常,或在其签名中添加合适的throw子句.以此类推.最终
得到的就是一个从软件最底端贯穿到最高端的修改链!封装被打破了,因为在抛出路径中的每个函数都要去了解下一层级的异常细节.既然异常旨在
让你能在较远处处理错误,可控异常以这种方式破坏封装简直就是一种耻辱.  
如果你在编写一套关键代码库,则可控异常有时也会有用:你必须捕获异常.但对于一般的应用开发,其依赖成本要高于收益.

#### 7.4 给出异常发生的环境说明
你抛出的每个异常,都应当提供足够的环境说明,以便判断错误的来源和住所.在Java中,你可以从任何异常里得到堆栈踪迹;然而,堆栈踪迹却无法
告诉你该失败操作的初衷.  
应创建信息充分的错误消息,并和异常一起传递出去.在消息中,包括失败的操作和失败类型.如果你的应用程序有日志系统,传递足够的信息给catch
块,并记录下来.

#### 7.5 依调用者需要定义异常类
对于错误分类有很多方式.可以依其来源分类:是来自组件还是其他地方?或依其类型分类:是设备错误、网络错误还是编程错误?不过,当我们在应
用程序中定义异常类时,最重要的考虑应该是它们如何被捕获.  
来看一个不太好的异常分类例子.下面的try-catch-finally语句是对某个第三方代码库的调用.它覆盖了该调用可能抛出的所有异常:  
```java
public class Test {
    public static void main(String[] args){
        ACMEPort port = new ACMEPort(12);
        try{
            port.open();
        } catch (DeviceResponseException e) {
            reportPortError(e);
            logger.log("Device response exception", e);
        } catch (ATM1212UnlockedException e) {
            reportPortError(e);
            logger.log("Unlocked exception", e);
        } catch (GMXError e) {
            reportPortError(e);
            logger.log("Device response exception", e);
        }
        finally{
            
        }
    }
}
```
语句包含了一大堆重复代码,这并不出奇.在大多数异常处理中,不管真实原因如何,我们总是做相对标准的处理.我们得记录错误,确保能继续工作.  
在本例中,既然知道我们所做的事不外如此,就可以通过打包调用API、确保它返回通用异常类型,从而简化代码.  
```java
public class Test {
    public static void main(String[] args){
      LocalPort port = new LocalPort(12);
      try{
          port.open();
      } catch (PortDeviceFailure e) {
          reportError(e);
          logger.log(e.getMessage(), e);
      } finally{
          //...
      }
    }
}
//LocalPort类就是个简单的打包类,捕获并翻译由ACMEPort类抛出的异常:
public class LocalPort {
    private ACMEPort innerPort;
    
    public LocalPort(int portNumber) {
        innerPort = new ACMEPort(portNumber);
    }
    public void open() {
        try{
            innerPort.open();
        } catch (DeviceResponseException e) {
            throw new PortDeviceFailure(e);
        } catch (ATM1212UnlockedException e) {
            throw new PortDeviceFailure(e);
        } catch (GMXError e) {
            throw new PortDeviceFailure(e);
        } finally{
            
        }
    }
}
```
类似我们为ACMEPort定义的这种打包类非常有用.实际上,将第三方API打包是个良好的实践手段.当你打包一个第三方API,你就降低了对它的依赖:
未来你可以不太痛苦地改用其他代码库.在你测试自己的代码时,打包也有助于模拟第三方调用.  
打包的好处还在于你不必绑死在某个特定厂商的API设计上.你可以定义自己感觉舒服的API.在上例中,我们为port设备错误定义了一个异常类型,
然后发现这样能写出更整洁的代码.  
对于代码的某个特定区域,单一异常通常可行.伴随异常发送出来的信息能区分不同错误.如果你想要捕获某个异常,并且放过其他异常,就使用不同
的异常类.

#### 7.6 定义常规流程
如果你遵循前文提及的建议,在业务逻辑和错误处理代码之间就会有良好的区隔.大量代码会开始变得像是整洁而简朴的算法.然而,这样做却把错误
检测推到了程序的边缘地带.你打包了外部API以抛出自己的异常,你在代码的顶端定义了一个处理器来应付任何失败了的运算.在大多数时候,这种
手段很棒,不过有时你也许不愿这么做.  
来看一个例子.下面的笨代码来自某个记账应用的开支总计模块:
```java
public class Test {
    public static void main(String[] args){
      try{
          MealExpenses expenses = expenseReportDAO.getMeals(employee.getID());
          m_total += expenses.getTotal();
      } catch (MealExpensesNotFound e) {
          m_total += getMealPerDiem();
      } finally{
          //...
      }
      /**
      *  业务逻辑是,如果消耗了餐盒,则计入总额中.如果没有消耗,则员工得到当日餐食补贴.异常打断了业务逻辑.如果不去处理特殊情况会不
      *  会好一些?那样的话代码看起来会更简洁.就像这样:
      */
      MealExpenses expenses = expenseReportDAO.getMeals(employee.getID());
      m_total += expenses.getTotal();
      /**
      *  能把代码写得那样简洁吗?能,可以修改ExpenseReportDAO,使之总是返回MealExpense对象.如果没有餐盒消耗,就返回一个返回餐盒补
      *  贴的MealExpense对象.
      */
    }
}
public class PerDiemMealExpenses implements MealExpenses {
    public int getTotal() {
        // return the per diem default
    }
}
```
这种手法叫做特例模式(SPECIAL CASE PATTERN).创建一个类或配置一个对象,用来处理特例,客户代码就不用应付异常行为了.异常行为被封装到
特例对象中.

#### 7.7 别返回null值
我认为,要讨论错误处理,就一定要提及哪些容易引发错误的做法.第一项就是返回null值.我不想去计算曾经见过多少几乎每行代码都在检查null
值的应用程序.下面就是个例子:  
```java
public class Main {
    public void register(Item item) {
        if (item != null) {
            ItemRegistry registry = peristentStore.getItemRegistry();
            if (registry != null) {
                Item existing = registry.getItem(item.getID());
                if (existing.getBillingPeriod().hasDetailOwner) {
                    existing.register(item);
                }
            }
        }
    }
}
```
返回null值,不仅给自己增加工作量,也是给调用者添乱.只要有一处没检查null值,应用程序就会失控.  
如果你打算在方法中返回null值,不如抛出异常,或是返回特例对象.如果你在调用某个第三方API中可能返回null值的方法,可以考虑用新方法打包
这个方法,在新方法抛出异常或返回特例对象.  
```java
public class Main {
    public void a() {
        /**
        * 设想有这么一段代码
        */
        List<Employee> employees = getEmployees();
        /**
        * todo 使用特例模式,去除空指针校验 
        * @See getEmployee()
        */
        if (employees != null) {
            for (Employee e : employees) {
                totalPay += e.getPay();
            }
        }
    }
    
    /**
    * 特例模式,解决空指针异常,代码更加整洁
    */
    public List<Employee> getEmployees() {
        if (thereAreaNoEmployees) {
            return Collections.emptyList();
        }
    }
}
```

#### 7.8 别传递null值
比返回null更加糟糕.除非API要求,否则尽可能不传递null值
```java
public class Main {
    /**
    * 计算两点的映射
    */
    public double xProjection(Point p1, Point p2) {
        return (p2.x - p1.x) * 1.5;
    }
    
    /**
    * 计算两点的映射
    * 处理空指针
    */
    public double xProjection(Point p1, Point p2) {
        if (p1 == null || p2 == null) {
            throw new InvalidAgrumentException("Invalid argument for MetricsCalculator.xProjection");
        }
        return (p2.x - p1.x) * 1.5;
    }
}
```
没有解决方案,只有在编码的时候,时时记住传递参数是否为null,从而避免这种无心之失.

#### 7.9 小结
整洁代码是可读的,但也要强固.可读与强固不冲突,因为可以将错误处理隔离看待,独立于主要逻辑之外.






















